#!/usr/bin/env python
#
# Copyright (C) 2019 Elexa Consumer Product, Inc.
#
# This file is part of the Guardian Device Simulator
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from daemonize import Daemonize

import click

import core
import devices


@click.group()
@click.version_option(version='0.1', prog_name='ges')
def ges():
    pass

@click.command()
def start_daemon():
    print('started')
    daemon.start()

@click.command()
def stop_daemon():
    print('stopped')
    daemon.exit()

ges.add_command(start_daemon)
ges.add_command(stop_daemon)

if __name__ == '__main__':
    ges()