#!/usr/bin/env python
#
# Copyright (C) 2019 Elexa Consumer Product, Inc.
#
# This file is part of the Guardian Device Simulator
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import socket
import time
import logging
import core

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server_address = ('localhost', 6000)
print('starting up on {} port {}'.format(*server_address))
sock.bind(server_address)

def gesd():
    """Guardian Ecosystem Simulator Daemon
    """
    while True:
        # Get the message
        data, address = sock.recvfrom(1024)

        print('received {} bytes from {}'.format(len(data), address))
        print(data)

if __name__ == "__main__":
    gesd()